import QUERY_PRODUCTS_USERS from "../queries/queryProductsUser.graphql";
export const productsWithUserMockData = [
  {
    request: {
      query: QUERY_PRODUCTS_USERS,
      variables: { id: "5" },
    },
    result: {
      data: {
        productList: [
          {
            id: "2",
            image_key: "SD_01_T38_1502_Y0_X_EC_0",
            name: "Round Neck Jumper",
            offer_ids: ["2", "3", "5", "4"],
            price: {
              currency_code: "GBP",
              current_price: 1250,
              original_price: 1400,
            },
          },
          {
            id: "3",
            image_key: "SD_01_T42_7049S_B4_X_EC_0",
            name: "Jersey Animal Print Swing Mini Dress",
            offer_ids: ["4", "1"],
            price: {
              currency_code: "GBP",
              current_price: 1500,
              original_price: 5000,
            },
          },
          {
            id: "4",
            image_key: "SD_01_T41_1519_Y0_X_EC_0",
            name: "Cotton Rich Scoop Neck Longline Vest Top",
            offer_ids: ["5", "4"],
            price: {
              currency_code: "GBP",
              current_price: 650,
              original_price: null,
            },
          },
          {
            id: "5",
            image_key: "SD_01_T42_5980_F0_X_EC_0",
            name: "Jersey Swing Midi Dress",
            offer_ids: ["2", "4", "3", "5"],
            price: {
              currency_code: "GBP",
              current_price: 1950,
              original_price: 2550,
            },
          },
          {
            id: "6",
            image_key: "SD_01_T43_4243_V4_X_EC_0",
            name: "Animal Print High Neck Long Sleeve Blouse",
            offer_ids: ["5", "2", "3"],
            price: {
              currency_code: "GBP",
              current_price: 2950,
              original_price: null,
            },
          },
          {
            id: "7",
            image_key: "SD_01_T57_7655_Y0_X_EC_0",
            name: "High Waist Cigarette Jeans",
            offer_ids: ["3", "1", "4", "2"],
            price: {
              currency_code: "GBP",
              current_price: 2950,
              original_price: null,
            },
          },
          {
            id: "8",
            image_key: "SD_01_T38_7685_HN_X_EC_0",
            name: "Textured Round Neck Jumper",
            offer_ids: ["5", "1", "4"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: null,
            },
          },
          {
            id: "9",
            image_key: "SD_01_T57_8675_GJ_X_EC_0",
            name: "Mid Rise Relaxed Slim Leg Jeans",
            offer_ids: ["5", "1"],
            price: {
              currency_code: "GBP",
              current_price: 2500,
              original_price: null,
            },
          },
          {
            id: "10",
            image_key: "SD_01_T38_2090_F4_X_EC_0",
            name: "Colour Block Jumper",
            offer_ids: ["4", "3", "5", "2"],
            price: {
              currency_code: "GBP",
              current_price: 2500,
              original_price: null,
            },
          },
          {
            id: "11",
            image_key: "SD_01_T57_3382L_NU_X_EC_0",
            name: "Pure Cotton Chino Shorts",
            offer_ids: ["5", "4"],
            price: {
              currency_code: "GBP",
              current_price: 1500,
              original_price: null,
            },
          },
          {
            id: "12",
            image_key: "SD_01_T59_6460_SW_X_EC_0",
            name: "Wide Leg Trousers",
            offer_ids: ["2"],
            price: {
              currency_code: "GBP",
              current_price: 2950,
              original_price: null,
            },
          },
          {
            id: "13",
            image_key: "SD_01_T59_7052_CB_X_EC_0",
            name: "Jersey A-Line Mini Skirt",
            offer_ids: ["3", "2", "4", "5"],
            price: {
              currency_code: "GBP",
              current_price: 1500,
              original_price: null,
            },
          },
          {
            id: "14",
            image_key: "SD_01_T43_4007U_F6_X_EC_0",
            name: "Polka Dot Round Neck Long Sleeve Blouse",
            offer_ids: ["3", "5"],
            price: {
              currency_code: "GBP",
              current_price: 2500,
              original_price: null,
            },
          },
          {
            id: "15",
            image_key: "SD_01_T59_5544_M0_X_EC_0",
            name: "Relaxed Straight Leg Trousers",
            offer_ids: ["3", "4"],
            price: {
              currency_code: "GBP",
              current_price: 2950,
              original_price: null,
            },
          },
          {
            id: "16",
            image_key: "SD_01_T57_8101_XB_X_EC_0",
            name: "High Waist Skinny Flare Jeans",
            offer_ids: ["2", "1", "4"],
            price: {
              currency_code: "GBP",
              current_price: 2500,
              original_price: null,
            },
          },
          {
            id: "17",
            image_key: "SD_01_T38_1015_Y0_X_EC_0",
            name: "Curved Hem High Neck Jumper",
            offer_ids: ["1", "4", "3", "2", "5"],
            price: {
              currency_code: "GBP",
              current_price: 1950,
              original_price: 4600,
            },
          },
          {
            id: "18",
            image_key: "SD_01_T41_5522_Y0_X_EC_0",
            name: "Ribbed High Neck Short Sleeve T-Shirt",
            offer_ids: ["2", "4", "5"],
            price: {
              currency_code: "GBP",
              current_price: 1750,
              original_price: null,
            },
          },
          {
            id: "19",
            image_key: "SD_01_T59_7911_M0_X_EC_0",
            name: "A-Line Midi Skirt",
            offer_ids: ["5"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: null,
            },
          },
          {
            id: "20",
            image_key: "SD_01_T41_1568_F4_X_EC_0",
            name: "Cotton Rich Striped Long Sleeve T-Shirt",
            offer_ids: ["1"],
            price: {
              currency_code: "GBP",
              current_price: 850,
              original_price: null,
            },
          },
          {
            id: "21",
            image_key: "SD_01_T38_7717B_F4_X_EC_0",
            name: "Pure Cotton Textured Round Neck Jumper",
            offer_ids: ["3", "4", "5"],
            price: {
              currency_code: "GBP",
              current_price: 1750,
              original_price: null,
            },
          },
          {
            id: "22",
            image_key: "SD_01_T42_7038S_Y0_X_EC_0",
            name: "V-Neck 3/4 Sleeve Shift Dress",
            offer_ids: ["2", "4"],
            price: {
              currency_code: "GBP",
              current_price: 1950,
              original_price: null,
            },
          },
          {
            id: "23",
            image_key: "SD_01_T38_2250_XO_X_EC_0",
            name: "Textured Turtle Neck Jumper",
            offer_ids: ["1", "4", "2", "5", "3"],
            price: {
              currency_code: "GBP",
              current_price: 2950,
              original_price: 4500,
            },
          },
          {
            id: "24",
            image_key: "SD_01_T38_1516_Y0_X_EC_0",
            name: "Round Neck Dolman Jumper",
            offer_ids: ["1", "5", "3"],
            price: {
              currency_code: "GBP",
              current_price: 1750,
              original_price: null,
            },
          },
          {
            id: "25",
            image_key: "SD_01_T41_8037Z_Z4_X_EC_0",
            name: "Pure Cotton Printed Short Sleeve T-Shirt",
            offer_ids: ["3"],
            price: {
              currency_code: "GBP",
              current_price: 650,
              original_price: null,
            },
          },
          {
            id: "26",
            image_key: "SD_01_T42_6999S_Y0_X_EC_0",
            name: "Long Sleeve Fit & Flare Mini Dress",
            offer_ids: ["1", "5"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: 5500,
            },
          },
          {
            id: "27",
            image_key: "SD_01_T41_7229_F0_X_EC_0",
            name: "V-Neck 3/4 Sleeve T-Shirt",
            offer_ids: ["5", "4"],
            price: {
              currency_code: "GBP",
              current_price: 2500,
              original_price: null,
            },
          },
          {
            id: "28",
            image_key: "SD_01_T59_6266_Y0_X_EC_0",
            name: "Ponte Wide Leg Trousers",
            offer_ids: ["4"],
            price: {
              currency_code: "GBP",
              current_price: 2500,
              original_price: null,
            },
          },
          {
            id: "29",
            image_key: "SD_01_T38_5598_Y0_X_EC_0",
            name: "Longline Cardigan",
            offer_ids: ["2", "1", "5"],
            price: {
              currency_code: "GBP",
              current_price: 2500,
              original_price: null,
            },
          },
          {
            id: "30",
            image_key: "SD_01_T57_7290_NZ_X_EC_0",
            name: "High Waist Wide Leg Cropped Jeans",
            offer_ids: ["2", "1", "5", "3"],
            price: {
              currency_code: "GBP",
              current_price: 2950,
              original_price: null,
            },
          },
          {
            id: "31",
            image_key: "SD_01_T49_8108A_DN_X_EC_0",
            name: "Scuba Fleece Jacket",
            offer_ids: ["5", "4", "2", "1", "3"],
            price: {
              currency_code: "GBP",
              current_price: 2950,
              original_price: null,
            },
          },
          {
            id: "32",
            image_key: "SD_01_T59_7054_T4_X_EC_0",
            name: "Animal Print Jersey A-Line Mini Skirt",
            offer_ids: ["4", "5", "3"],
            price: {
              currency_code: "GBP",
              current_price: 1500,
              original_price: null,
            },
          },
          {
            id: "33",
            image_key: "SD_01_T41_7254_Y0_X_EC_0",
            name: "Ribbed Round Neck Open Knit T-Shirt",
            offer_ids: ["4", "5", "3"],
            price: {
              currency_code: "GBP",
              current_price: 2250,
              original_price: null,
            },
          },
          {
            id: "34",
            image_key: "SD_01_T43_5668_Y0_X_EC_0",
            name: "High Neck Long Sleeve Blouse",
            offer_ids: ["3", "2"],
            price: {
              currency_code: "GBP",
              current_price: 2750,
              original_price: null,
            },
          },
          {
            id: "35",
            image_key: "SD_01_T41_5523_F0_X_EC_0",
            name: "Super Soft Round Neck Long Sleeve T-Shirt",
            offer_ids: ["4", "3"],
            price: {
              currency_code: "GBP",
              current_price: 1950,
              original_price: null,
            },
          },
          {
            id: "36",
            image_key: "SD_01_T42_6975S_S9_X_EC_0",
            name: "Animal Print Long Sleeve Wrap Midi Dress",
            offer_ids: ["2", "5", "3", "1", "4"],
            price: {
              currency_code: "GBP",
              current_price: 4950,
              original_price: null,
            },
          },
          {
            id: "37",
            image_key: "SD_01_T41_8594_F0_X_EC_90",
            name: "High Neck Short Sleeve T-Shirt",
            offer_ids: ["1"],
            price: {
              currency_code: "GBP",
              current_price: 650,
              original_price: null,
            },
          },
          {
            id: "38",
            image_key: "SD_01_T41_7198_NM_X_EC_0",
            name: "Ribbed V-Neck Cardigan",
            offer_ids: ["4", "3", "2"],
            price: {
              currency_code: "GBP",
              current_price: 2500,
              original_price: null,
            },
          },
          {
            id: "39",
            image_key: "SD_01_T38_2440_Y0_X_EC_0",
            name: "Knitted Skirt",
            offer_ids: ["3", "4", "1", "5"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: null,
            },
          },
          {
            id: "40",
            image_key: "SD_01_T57_6170_PK_X_EC_0",
            name: "Animal Print Jersey Slim Leg Trousers",
            offer_ids: ["3"],
            price: {
              currency_code: "GBP",
              current_price: 2750,
              original_price: null,
            },
          },
          {
            id: "41",
            image_key: "SD_01_T42_6980S_S9_X_EC_0",
            name: "Animal Print Long Sleeve Shirt Midi Dress",
            offer_ids: ["3", "5", "2", "1", "4"],
            price: {
              currency_code: "GBP",
              current_price: 4500,
              original_price: null,
            },
          },
          {
            id: "42",
            image_key: "SD_01_T41_8001E_B5_X_EC_0",
            name: "CURVE Round Neck 3/4 Sleeve Tunic",
            offer_ids: ["1", "5", "3", "4"],
            price: {
              currency_code: "GBP",
              current_price: 1950,
              original_price: null,
            },
          },
          {
            id: "43",
            image_key: "SD_01_T38_5183T_VK_X_EC_0",
            name: "Ribbed Turtle Neck Jumper",
            offer_ids: ["1", "2"],
            price: {
              currency_code: "GBP",
              current_price: 4500,
              original_price: null,
            },
          },
          {
            id: "44",
            image_key: "SD_01_T59_1572S_Y0_X_EC_90",
            name: "A-Line Mini Skirt",
            offer_ids: ["4", "1"],
            price: {
              currency_code: "GBP",
              current_price: 1500,
              original_price: null,
            },
          },
          {
            id: "45",
            image_key: "SD_01_T38_2480_F0_X_EC_0",
            name: "Textured Roll Neck Knitted Dress",
            offer_ids: ["3"],
            price: {
              currency_code: "GBP",
              current_price: 3950,
              original_price: null,
            },
          },
          {
            id: "46",
            image_key: "SD_01_T49_1824_UT_X_EC_0",
            name: "Single Breasted Coat",
            offer_ids: ["4", "3"],
            price: {
              currency_code: "GBP",
              current_price: 4950,
              original_price: null,
            },
          },
          {
            id: "47",
            image_key: "SD_01_T59_6611_Y0_X_EC_90",
            name: "Wide Leg Ankle Grazer Trousers",
            offer_ids: ["5"],
            price: {
              currency_code: "GBP",
              current_price: 3950,
              original_price: null,
            },
          },
          {
            id: "48",
            image_key: "SD_01_T59_5545_M4_X_EC_90",
            name: "Checked Straight Leg Trousers",
            offer_ids: ["2", "4", "5", "1"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: null,
            },
          },
          {
            id: "49",
            image_key: "SD_01_T57_6992S_Y4_X_EC_0",
            name: "Tapered Leg Ankle Grazer Joggers",
            offer_ids: ["1", "2"],
            price: {
              currency_code: "GBP",
              current_price: 2500,
              original_price: null,
            },
          },
          {
            id: "50",
            image_key: "SD_01_T57_7062_KH_X_EC_0",
            name: "High Waist Skinny Leg Trousers",
            offer_ids: ["1", "5", "2", "3"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: null,
            },
          },
          {
            id: "51",
            image_key: "SD_01_T38_2830_K7_X_EC_0",
            name: "Animal Print Round Neck Jumper",
            offer_ids: ["5", "1", "4"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: null,
            },
          },
          {
            id: "52",
            image_key: "SD_01_T42_1006E_Y0_X_EC_0",
            name: "CURVE Short Sleeve Column Maxi Dress",
            offer_ids: ["5", "4", "3", "1"],
            price: {
              currency_code: "GBP",
              current_price: 2250,
              original_price: null,
            },
          },
          {
            id: "53",
            image_key: "SD_01_T57_6998_Y4_X_EC_0",
            name: "Polka Dot Jersey Peg Trousers",
            offer_ids: ["1", "5", "2"],
            price: {
              currency_code: "GBP",
              current_price: 2250,
              original_price: null,
            },
          },
          {
            id: "54",
            image_key: "SD_01_T59_7074_E4_X_EC_90",
            name: "Checked A-Line Mini Skirt",
            offer_ids: ["1", "4", "5", "3", "2"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: null,
            },
          },
          {
            id: "55",
            image_key: "SD_01_T41_5525_Y4_X_EC_0",
            name: "Pure Cotton Striped Slash Neck Sweatshirt",
            offer_ids: ["3"],
            price: {
              currency_code: "GBP",
              current_price: 2250,
              original_price: null,
            },
          },
          {
            id: "56",
            image_key: "SD_01_T41_1617_R4_X_EC_0",
            name: "Printed Round Neck Vest Top",
            offer_ids: ["4", "3"],
            price: {
              currency_code: "GBP",
              current_price: 850,
              original_price: null,
            },
          },
          {
            id: "57",
            image_key: "SD_01_T59_4025U_F4_X_EC_0",
            name: "Polka Dot Pleated Midi Skirt",
            offer_ids: ["3", "5", "2", "4", "1"],
            price: {
              currency_code: "GBP",
              current_price: 4500,
              original_price: null,
            },
          },
          {
            id: "58",
            image_key: "SD_01_T38_1491_Y0_X_EC_0",
            name: "Button Through V-Neck Cardigan",
            offer_ids: ["1", "3"],
            price: {
              currency_code: "GBP",
              current_price: 1950,
              original_price: null,
            },
          },
          {
            id: "59",
            image_key: "SD_01_T42_6987S_Y0_X_EC_0",
            name: "Jersey Long Sleeve Wrap Dress",
            offer_ids: ["5", "2"],
            price: {
              currency_code: "GBP",
              current_price: 2500,
              original_price: null,
            },
          },
          {
            id: "60",
            image_key: "SD_01_T42_3208U_E4_X_EC_90",
            name: "Animal Print Jersey Bodycon Dress",
            offer_ids: ["3", "5", "4", "2", "1"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: null,
            },
          },
          {
            id: "61",
            image_key: "SD_01_T38_1514A_E4_X_EC_0",
            name: "Cashmilon™ Printed V-Neck Jumper",
            offer_ids: ["2", "1", "4", "5", "3"],
            price: {
              currency_code: "GBP",
              current_price: 1750,
              original_price: null,
            },
          },
          {
            id: "62",
            image_key: "SD_01_T38_5557_K4_X_EC_0",
            name: "Cashmilon™ Textured Round Neck Jumper",
            offer_ids: ["3"],
            price: {
              currency_code: "GBP",
              current_price: 1750,
              original_price: null,
            },
          },
          {
            id: "63",
            image_key: "SD_01_T43_4975_F0_X_EC_0",
            name: "Polka Dot Long Sleeve Shirt",
            offer_ids: ["4"],
            price: {
              currency_code: "GBP",
              current_price: 1750,
              original_price: null,
            },
          },
          {
            id: "64",
            image_key: "SD_01_T38_2360_UT_X_EC_0",
            name: "Textured Hooded Jumper",
            offer_ids: ["2", "3", "1", "4"],
            price: {
              currency_code: "GBP",
              current_price: 2950,
              original_price: null,
            },
          },
          {
            id: "65",
            image_key: "SD_01_T59_5542_Y0_X_EC_0",
            name: "Side Stripe Relaxed Straight Leg Trousers",
            offer_ids: ["4"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: null,
            },
          },
          {
            id: "66",
            image_key: "SD_01_T49_1603E_Y0_X_EC_0",
            name: "CURVE Single Breasted Coat",
            offer_ids: ["2", "1"],
            price: {
              currency_code: "GBP",
              current_price: 7900,
              original_price: null,
            },
          },
          {
            id: "67",
            image_key: "SD_01_T41_8052_Y0_X_EC_90",
            name: "High Neck Vest Top",
            offer_ids: ["2"],
            price: {
              currency_code: "GBP",
              current_price: 650,
              original_price: null,
            },
          },
          {
            id: "68",
            image_key: "SD_01_T41_8774_ZZ_X_EC_0",
            name: "Pure Cotton Printed Short Sleeve T-Shirt",
            offer_ids: ["5", "1", "3", "2"],
            price: {
              currency_code: "GBP",
              current_price: 850,
              original_price: null,
            },
          },
          {
            id: "69",
            image_key: "SD_01_T57_7082_T4_X_EC_90",
            name: "Pure Linen Ankle Grazer Peg Trousers",
            offer_ids: ["5"],
            price: {
              currency_code: "GBP",
              current_price: 2950,
              original_price: null,
            },
          },
          {
            id: "70",
            image_key: "SD_01_T38_4924_DC_X_EC_0",
            name: "Twinset Cardigan",
            offer_ids: ["2", "5", "1", "3", "4"],
            price: {
              currency_code: "GBP",
              current_price: 1600,
              original_price: null,
            },
          },
          {
            id: "71",
            image_key: "SD_01_T41_8036Z_ZZ_X_EC_0",
            name: "Pure Cotton Striped Short Sleeve T-Shirt",
            offer_ids: ["2", "4", "5", "1", "3"],
            price: {
              currency_code: "GBP",
              current_price: 650,
              original_price: null,
            },
          },
          {
            id: "72",
            image_key: "SD_01_T43_2301T_A4_X_EC_0",
            name: "Printed Long Sleeve Shirt",
            offer_ids: ["3", "5", "4"],
            price: {
              currency_code: "GBP",
              current_price: 3950,
              original_price: 4500,
            },
          },
          {
            id: "73",
            image_key: "SD_01_T42_7000P_CB_X_EC_0",
            name: "PETITE Long Sleeve Fit & Flare Dress",
            offer_ids: ["2", "4", "3", "5", "1"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: null,
            },
          },
          {
            id: "74",
            image_key: "SD_01_T49_4315_Y4_X_EC_0",
            name: "Padded Jacket",
            offer_ids: ["3", "1"],
            price: {
              currency_code: "GBP",
              current_price: 4950,
              original_price: null,
            },
          },
          {
            id: "75",
            image_key: "SD_01_T42_5969_T4_X_EC_0",
            name: "Animal Print Short Sleeve Shift Midi Dress",
            offer_ids: ["5", "3", "1", "2", "4"],
            price: {
              currency_code: "GBP",
              current_price: 2950,
              original_price: null,
            },
          },
          {
            id: "76",
            image_key: "SD_01_T41_8010E_E0_X_EC_0",
            name: "CURVE Round Neck Short Sleeve Tunic",
            offer_ids: ["1", "5", "4"],
            price: {
              currency_code: "GBP",
              current_price: 2250,
              original_price: null,
            },
          },
          {
            id: "77",
            image_key: "SD_01_T38_2870_QE_X_EC_0",
            name: "Cable Knit Turtle Neck Jumper",
            offer_ids: ["4", "5", "1", "3", "2"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: null,
            },
          },
          {
            id: "78",
            image_key: "SD_01_T57_8008_F4_X_EC_90",
            name: "Jersey Pencil Maxi Skirt",
            offer_ids: ["2", "4", "3"],
            price: {
              currency_code: "GBP",
              current_price: 2250,
              original_price: null,
            },
          },
          {
            id: "79",
            image_key: "SD_01_T57_3381S_NU_X_EC_0",
            name: "Pure Cotton Chino Shorts",
            offer_ids: ["2"],
            price: {
              currency_code: "GBP",
              current_price: 1500,
              original_price: null,
            },
          },
          {
            id: "80",
            image_key: "SD_01_T59_6608_Y0_X_EC_0",
            name: "Slim Bootcut Leg Trousers",
            offer_ids: ["5", "3", "4"],
            price: {
              currency_code: "GBP",
              current_price: 2950,
              original_price: null,
            },
          },
          {
            id: "81",
            image_key: "SD_01_T57_6176_F4_X_EC_90",
            name: "Textured Jersey Wide Leg Trousers",
            offer_ids: ["1", "5"],
            price: {
              currency_code: "GBP",
              current_price: 2750,
              original_price: null,
            },
          },
          {
            id: "82",
            image_key: "SD_01_T42_6000_P4_X_EC_0",
            name: "Striped Shift Mini Dress",
            offer_ids: ["2", "1"],
            price: {
              currency_code: "GBP",
              current_price: 2500,
              original_price: null,
            },
          },
          {
            id: "83",
            image_key: "SD_01_T57_6997_KA_X_EC_0",
            name: "Jersey Tapered Peg Trousers",
            offer_ids: ["5"],
            price: {
              currency_code: "GBP",
              current_price: 2250,
              original_price: null,
            },
          },
          {
            id: "84",
            image_key: "SD_01_T57_9489_XU_X_EC_0",
            name: "Denim Skirt",
            offer_ids: ["1"],
            price: {
              currency_code: "GBP",
              current_price: 2950,
              original_price: null,
            },
          },
          {
            id: "85",
            image_key: "SD_01_T59_1572J_Y0_X_EC_0",
            name: "Single Breasted Blazer",
            offer_ids: ["4", "3", "1"],
            price: {
              currency_code: "GBP",
              current_price: 2950,
              original_price: 4500,
            },
          },
          {
            id: "86",
            image_key: "SD_01_T38_2470_K4_X_EC_0",
            name: "Striped Turtle Neck Jumper",
            offer_ids: ["3"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: null,
            },
          },
          {
            id: "87",
            image_key: "SD_01_T59_5021T_Y0_X_EC_0",
            name: "Cotton Rich Tapered Leg Peg Trousers",
            offer_ids: ["3", "5", "1", "2", "4"],
            price: {
              currency_code: "GBP",
              current_price: 4950,
              original_price: null,
            },
          },
          {
            id: "88",
            image_key: "SD_01_T59_7994_F3_X_EC_90",
            name: "Jersey Pleated Midi Skirt",
            offer_ids: ["4", "5"],
            price: {
              currency_code: "GBP",
              current_price: 2500,
              original_price: null,
            },
          },
          {
            id: "89",
            image_key: "SD_01_T59_7912_T4_X_EC_90",
            name: "Checked A-Line Midi Skirt",
            offer_ids: ["5"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: null,
            },
          },
          {
            id: "90",
            image_key: "SD_01_T41_8034Z_F4_X_EC_0",
            name: "Pure Cotton Printed Short Sleeve T-Shirt",
            offer_ids: ["4", "1", "3"],
            price: {
              currency_code: "GBP",
              current_price: 650,
              original_price: null,
            },
          },
          {
            id: "91",
            image_key: "SD_01_T43_1342_F4_X_EC_0",
            name: "Striped Oversized Long Sleeve Shirt",
            offer_ids: ["2", "4", "5", "1", "3"],
            price: {
              currency_code: "GBP",
              current_price: 2950,
              original_price: null,
            },
          },
          {
            id: "92",
            image_key: "SD_01_T02_0050A_Y0_X_EC_0",
            name: "Wedge Heel Mule Shoes",
            offer_ids: ["3", "5", "2", "4"],
            price: {
              currency_code: "GBP",
              current_price: 1950,
              original_price: null,
            },
          },
          {
            id: "93",
            image_key: "SD_01_T41_1217_E4_X_EC_0",
            name: "Cotton Rich Striped Short Sleeve T-Shirt",
            offer_ids: ["2"],
            price: {
              currency_code: "GBP",
              current_price: 650,
              original_price: null,
            },
          },
          {
            id: "94",
            image_key: "SD_01_T59_5506_F4_X_EC_0",
            name: "Checked Relaxed Straight Leg Crepe Trousers",
            offer_ids: ["1", "4"],
            price: {
              currency_code: "GBP",
              current_price: 3500,
              original_price: 4500,
            },
          },
          {
            id: "95",
            image_key: "SD_01_T57_6169_F4_X_EC_0",
            name: "Textured Ankle Grazer Trousers",
            offer_ids: ["5", "3", "1"],
            price: {
              currency_code: "GBP",
              current_price: 2750,
              original_price: null,
            },
          },
          {
            id: "96",
            image_key: "SD_01_T59_0586J_E4_X_EC_0",
            name: "Checked Open Front Blazer",
            offer_ids: ["4", "2", "3", "1"],
            price: {
              currency_code: "GBP",
              current_price: 6900,
              original_price: null,
            },
          },
          {
            id: "97",
            image_key: "SD_01_T41_1391_B0_X_EC_0",
            name: "Pure Cotton Scoop Neck Vest Top",
            offer_ids: ["4", "5"],
            price: {
              currency_code: "GBP",
              current_price: 450,
              original_price: null,
            },
          },
        ],
        user: {
          id: "5",
          available_badges:
            "gonesoon:REDUCED||sale:PRIORITY_ACCESS||loyalty:SLOTTED,BONUS",
          offers: [
            {
              id: "1",
              title: "Get it while it lasts!",
              type: "REDUCED",
            },
            {
              id: "2",
              title: "Extra loyalty points!",
              type: "BONUS",
            },
            {
              id: "3",
              title: "Priority Access!",
              type: "PRIORITY_ACCESS",
            },
            {
              id: "4",
              title: "Discount available!",
              type: "SLOTTED",
            },
            {
              id: "5",
              title: "Super sale!",
              type: "BONUS",
            },
          ],
        },
      },
    },
  },
];
